# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LLPhotoPicker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LLPhotoPicker
  pod 'Masonry','1.0.2'
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'YYAsyncLayer'
  # pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.5'

end
